server:
  port: 60241

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/Practicum/sprint20/infra/config-server/src/main/resources/config/telemetry/{application},
            file:///D:/Practicum/sprint20/infra/config-server/src/main/resources/config/commerce/{application}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}