# ??????
server.port=8080
# ???????????
logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework.web=INFO
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
# ?????? Kafka
kafka.topics.sensor-events=telemetry.sensors.v1
kafka.topics.hub-events=telemetry.hubs.v1
# gRPC
grpc.server.port=59091