# ??????
server.port=8080
# ???????????
logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework.web=INFO
# Kafka ?????????
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# ?????? Kafka
kafka.topics.sensor-events=sensor-events
kafka.topics.hub-events=hub-events
# Jackson ????????? ??? JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
# ????????? ??????????
app.name=telemetry-collector
app.version=1.0.0