server:
  port: 8081

spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-local
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 20
    producer:
      batch-size: 8192
      linger-ms: 50
      max-in-flight-requests-per-connection: 10

kafka:
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

app:
  aggregation:
    poll-timeout: 1000
    shutdown-timeout: 5000

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG
    org.apache.kafka.clients.producer: DEBUG