spring.application.name=analyzer

# ===== H2 DATABASE =====
spring.datasource.url=jdbc:h2:mem:analyzer_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ===== SQL INIT - ???????????? schema-h2.sql =====
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-h2.sql

# ===== H2 CONSOLE =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# ===== KAFKA =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analyzer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# ===== GRPC =====
grpc.client.hub-router.address=static://localhost:9090
grpc.client.hub-router.negotiation-type=plaintext

# ===== ????????? ??????????? =====
analyzer.kafka.bootstrap-servers=localhost:9092

analyzer.snapshot.consumer.group-id=analyzer-snapshot-group
analyzer.snapshot.consumer.auto-offset-reset=earliest
analyzer.snapshot.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.snapshot.consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.event.SensorsSnapshotAvroDeserializer

analyzer.hub-event.consumer.group-id=analyzer-hub-event-group
analyzer.hub-event.consumer.auto-offset-reset=earliest
analyzer.hub-event.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.hub-event.consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.event.HubEventAvroDeserializer

# ===== ??????????? =====
logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=DEBUG