-- создаём таблицу scenarios
CREATE TABLE IF NOT EXISTS scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT unique_hub_scenario UNIQUE(hub_id, name)
);

-- создаём таблицу sensors
CREATE TABLE IF NOT EXISTS sensors (
    id VARCHAR(255) PRIMARY KEY,
    hub_id VARCHAR(255)
);

-- создаём таблицу conditions
CREATE TABLE IF NOT EXISTS conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    operation VARCHAR(255),
    value_int INTEGER
);

-- создаём таблицу actions
CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    value_int INTEGER
);

CREATE TABLE IF NOT EXISTS scenario_conditions (
    scenario_id BIGINT,
    sensor_id VARCHAR(255),
    condition_id BIGINT,
    PRIMARY KEY (scenario_id, sensor_id, condition_id),
    FOREIGN KEY (scenario_id) REFERENCES scenarios(id),
    FOREIGN KEY (sensor_id) REFERENCES sensors(id),
    FOREIGN KEY (condition_id) REFERENCES conditions(id)
);

CREATE TABLE IF NOT EXISTS scenario_actions (
    scenario_id BIGINT,
    sensor_id VARCHAR(255),
    action_id BIGINT,
    PRIMARY KEY (scenario_id, sensor_id, action_id),
    FOREIGN KEY (scenario_id) REFERENCES scenarios(id),
    FOREIGN KEY (sensor_id) REFERENCES sensors(id),
    FOREIGN KEY (action_id) REFERENCES actions(id)
);