spring:
  server:
    port: 59090

  grpc:
    server:
      port: 59091

  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092


kafka:
  topics:
    sensor-events: telemetry.sensors.v1
    hub-events: telemetry.hubs.v1

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/