spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: shopping-store_service_route
          uri: lb://SHOPPING-STORE
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND, INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                methods: GET
                exceptions: ru.yandex.practicum.exception.ProductNotFoundException
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: true