spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://SHOPPING-CART
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

        - id: shopping-store_service_route
          uri: lb://SHOPPING-STORE
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1

        - id: warehouse_service_route
          uri: lb://WAREHOUSE
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1

        - id: order_service_route
          uri: lb://ORDER
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1

server:
  port: 8080